### ISSUE TITLE
ModuleNotFoundError: No module named 'mock'

### ISSUE THREAD

**Issue by lourot** [openstack-charmers/magpie-layer#24]
```
juju deploy ~openstack-charmers-next/magpie
```

leads to

```
2020-12-14 10:25:12 INFO juju-log Reactive main running for hook install
2020-12-14 10:25:12 ERROR juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-magpie-0/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 71, in main
    bus.discover()
  File "/var/lib/juju/agents/unit-magpie-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 426, in discover
    _register_handlers_from_file(search_path, filepath)
  File "/var/lib/juju/agents/unit-magpie-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 466, in _register_handlers_from_file
    _load_module(root, filepath)
  File "/var/lib/juju/agents/unit-magpie-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 444, in _load_module
    return importlib.import_module(package + module)
  File "/var/lib/juju/agents/unit-magpie-0/.venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/juju/agents/unit-magpie-0/charm/hooks/relations/magpie/unit_tests/test_peers.py", line 18, in <module>
    import mock
ModuleNotFoundError: No module named 'mock'
```

Also seen on OSCI: http://osci:8080/job/test_charm_func_smoke/20193/console

**Comment by lourot** [comment]
Fix: https://review.opendev.org/c/openstack/charm-interface-magpie/+/766967

**Comment by lourot** [comment]
The fix has landed and a new `charm-magpie` version now needs to be published. For this we need https://github.com/openstack-charmers/bot-control/pull/197

**Comment by lourot** [comment]
Published: https://jaas.ai/u/openstack-charmers-next/magpie/5
